package:
  name: netgen
  version: 6.2

requirements:
  build:
    - python 3.6.1
    - jpeg
    - cmake
    - git
    - tk
    - xorg-libxmu # [not win]
  run:
    - python 3.6.1
    - jpeg
    - tk
    - zlib
    - xorg-libxmu # [not win]

source:
  git_url: https://git.code.sf.net/p/netgen-mesher/git
  patches:
    togl.patch


about:
  home: bla
  license: LGPL
