package:
  name: netgen
  version: 6.2

requirements:
  build:
    - python 3.6.1
    - jpeg
    - cmake
    - tk
    - xorg-libxmu
  run:
    - python 3.6.1
    - jpeg
    - tk
    - xorg-libxmu

source:
  git_url: https://git.code.sf.net/p/netgen-mesher/git
  patches:
    togl.patch


about:
  home: bla
  license: LGPL
